### ISSUE TITLE
Instruction

### ISSUE THREAD

**Issue by samansarraf** [jingweimo/Modified-LSTM#3]
Thanks for providing the code. I was trying to the run the code but getting some errors. Just to know if I'm in right track, I wonder if we need to replace recurrent.py of Keras with your corresponding file and recompile Keras? Is that correct? 
If that's the case , I'm getting the following error : 
_Using Theano backend.
LSTM1 is being used...
LSTM2 is being used...
LSTM3 is being used...
X_train shape: (60000, 784, 1)
60000 train samples
10000 test samples
Traceback (most recent call last):
  File "./mnistimdblstm.py", line 95, in <module>
    consume_less=consume_less)) 
  File "/usr/local/lib/python3.4/dist-packages/Keras-2.0.6-py3.4.egg/keras/models.py", line 436, in add
  File "/usr/local/lib/python3.4/dist-packages/Keras-2.0.6-py3.4.egg/keras/engine/topology.py", line 569, in __call__
  File "/usr/local/lib/python3.4/dist-packages/Keras-2.0.6-py3.4.egg/keras/layers/recurrent.py", line 946, in build
    self.U_i = self.inner_init((self.output_dim, self.output_dim),
TypeError: __call__() got an unexpected keyword argument 'name'_

Just FYI , I can run the Keras examples without an issue. 
Thanks,
S.

**Comment by jingweimo** [comment]
What keras version do you use? That code is based on `keras <2.0`. I will updated it for latest keras later.

**Comment by jingweimo** [comment]
@samansarraf : please check the updated file and comments for your implementation environments

**Comment by samansarraf** [comment]
Thanks for updating the code . I will give it a try and will keep you
posted .

Best,
Saman

*Saman Sarraf*
Algorithm Engineer, SMIEEE
Machine Learning & Imaging Scientist
Konica Minolta
[image: https://www.linkedin.com/in/sarrafsaman/]
<https://www.linkedin.com/in/sarrafsaman/>

**Comment by ebbilgin** [comment]
@samansarraf If you solved the issue can you tell me what steps should I take to change the recurrent.py and recompile Keras?

Best,
Enes
